# Generated by Django 4.1.7 on 2023-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default='', max_length=20, verbose_name='이름')),
                ('username', models.CharField(default='', max_length=20, unique=True, verbose_name='아이디')),
                ('age', models.CharField(default='', max_length=20, verbose_name='나이')),
                ('tall', models.CharField(default='', max_length=20, verbose_name='키')),
                ('gender', models.CharField(default='', max_length=20, verbose_name='성별')),
                ('exercise', models.CharField(default='', max_length=100, verbose_name='운동 여부')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'common',
                'db_table': 'UserCommon',
            },
        ),
    ]
