# Generated by Django 4.1.7 on 2023-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='exercise',
            field=models.CharField(choices=[('every', '일주일에 운동을 매일 합니다.'), ('four', '일주일에 4~5번합니다.'), ('three', '일주일에 3~4번합니다.'), ('one', '일주일에 1~2번합니다.'), ('no', '일주일에 운동을 안합니다.')], default='', max_length=20, verbose_name='운동여부'),
        ),
    ]
