# Generated by Django 4.1.7 on 2023-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_common_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='exercise',
            field=models.CharField(default='', max_length=100, verbose_name='운동여부'),
        ),
    ]
