# Generated by Django 4.1.7 on 2023-05-29 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=20, verbose_name='체중')),
                ('fat', models.CharField(max_length=20, verbose_name='체지방량')),
                ('muscle', models.CharField(max_length=20, verbose_name='골격근량')),
                ('target_weight', models.CharField(max_length=20, verbose_name='목표체중')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'setting',
                'db_table': 'UserSetting',
            },
        ),
    ]
