# Generated by Django 4.1.7 on 2023-05-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie',
            old_name='user_id',
            new_name='user',
        ),
    ]
