# Generated by Django 4.1.7 on 2023-05-23 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0004_rename_user_calorie_calorie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie',
            name='calorie_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
