# Generated by Django 4.1.7 on 2023-05-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_calorie_calorie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorie',
            name='eat_calorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.food', verbose_name='섭취한 칼로리'),
            preserve_default=False,
        ),
    ]
