# Generated by Django 4.1.7 on 2023-05-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_calorie_calorie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie',
            name='eat_calorie',
            field=models.CharField(max_length=5, verbose_name='섭취한 칼로리'),
        ),
    ]
