# Generated by Django 4.1.7 on 2023-06-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_calorie_eat_calorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie',
            old_name='calorie_user',
            new_name='user',
        ),
    ]
